# guition-35-display.yaml

esphome:
  name: guition-display
  friendly_name: Guition Display

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

substitutions:
  home_page: meine_lampen  # ← Deine neue Seite als Startseite

packages:
  device: !include devices/JC3248W535.yaml
  common: !include common.yaml
  layout: !include layouts/480x320.yaml
  meine_lampen: !include meine-lampen.yaml  # ← Neue Datei einbinden

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "Guition Fallback"
    password: "12345678"

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password