esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "31Ep+SbSTd2LVWYPTnjjGjLu9aycgru2TRk6XpRk2X8="

ota:
  - platform: esphome
    password: "0465db0eea6ba9c9b8dced016a7b9cee"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "4fpFbIKvrVX6"

captive_portal:
    